name: Docker Build Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PRODUCT_REPO_NAME: rrequero
  EKS_CLUSTER_NAME: cc-k8s
  AWS_REGION: ap-southeast-2
  DOCKER_IMAGE: flask-app
jobs:
  create-user-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Work Dir
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $PRODUCT_REPO_NAME
      - name: Docker login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build user service docker image
        run: docker build . --file Dockerfile -t "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"
      - name: Push user service docker image
        run: docker push "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"
  deployment:
    needs: [create-user-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ap-southeast-2
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: arn:aws:iam::544863999112:role/GitHubAction-AssumeRoleWithAction
      # Hello from AWS: WhoAmI
      # - name: Sts GetCallerIdentity
      #   run: |
      #     aws sts get-caller-identity
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      # - name: Update kubectl
      #   run: |
      #     curl -LO "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl"
      #     chmod +x kubectl
      #     sudo mv kubectl /usr/local/bin/
      - name: Apply Kubernetes manifest
        run: kubectl apply -f k8s/ -v=8
